export type PlanetMetric = {
  label: string;
  value: string;
};

export type PlanetOrbitStatus = {
  label: string;
  value: string;
};

export type PlanetProfile = {
  id: string;
  order: string;
  name: string;
  englishName: string;
  title: string;
  subtitle: string;
  description: string;
  insight: string;
  metrics: PlanetMetric[];
  orbitStatus: PlanetOrbitStatus[];
  orbitRadius: number;
  radius: number;
  semiMajorAxisAu: number;
  orbitalEccentricity: number;
  orbitalInclinationDeg: number;
  orbitalPeriodDays: number;
  initialAngle: number;
  orbitSpeed: number;
  rotationSpeed: number;
  inclination: number;
  color: string;
  accent: string;
  glow: string;
  shadow: string;
  ring?: boolean;
  textureMode: 'crater' | 'cloud' | 'bands' | 'storm' | 'ice' | 'ocean';
};

export const planets: PlanetProfile[] = [
  {
    id: 'mercury',
    order: '01',
    name: '水星',
    englishName: 'Mercury',
    title: '太阳最近的高速信使',
    subtitle: '岩质行星 / 极端昼夜',
    description: '它贴着太阳疾行，表面布满陨石坑。没有厚重大气保护，白昼与黑夜像两种完全不同的世界。',
    insight: '拖拽星图时，水星会最先显出轨道速度的锐利感。',
    metrics: [
      { label: '平均距离 (AU)', value: '0.39' },
      { label: '公转周期', value: '88 天' },
      { label: '自转周期', value: '58.6 天' },
      { label: '直径', value: '4,879 km' },
      { label: '表面重力', value: '3.7 m/s²' },
      { label: '卫星数量', value: '0' },
    ],
    orbitStatus: [
      { label: '速度', value: '47.4 km/s' },
      { label: '轨道偏心率', value: '0.206' },
      { label: '近日点', value: '0.31 AU' },
      { label: '远日点', value: '0.47 AU' },
    ],
    orbitRadius: 2.7,
    radius: 0.22,
    semiMajorAxisAu: 0.387,
    orbitalEccentricity: 0.206,
    orbitalInclinationDeg: 7.0,
    orbitalPeriodDays: 87.97,
    initialAngle: 20,
    orbitSpeed: 0.54,
    rotationSpeed: 0.005,
    inclination: 0.16,
    color: '#b9afa0',
    accent: '#f0c882',
    glow: '#f6d99f',
    shadow: '#4a463f',
    textureMode: 'crater',
  },
  {
    id: 'venus',
    order: '02',
    name: '金星',
    englishName: 'Venus',
    title: '被金色云海包裹的热岛',
    subtitle: '岩质行星 / 浓厚大气',
    description: '金星的云层反射强烈阳光，表面温度极高。它缓慢逆向自转，像一颗发光的密封温室。',
    insight: '打开标签后，金星的暖色轨迹会形成第二层视觉节奏。',
    metrics: [
      { label: '平均距离 (AU)', value: '0.72' },
      { label: '公转周期', value: '225 天' },
      { label: '自转周期', value: '243 天' },
      { label: '直径', value: '12,104 km' },
      { label: '平均温度', value: '464°C' },
      { label: '卫星数量', value: '0' },
    ],
    orbitStatus: [
      { label: '速度', value: '35.0 km/s' },
      { label: '轨道偏心率', value: '0.007' },
      { label: '近日点', value: '0.72 AU' },
      { label: '远日点', value: '0.73 AU' },
    ],
    orbitRadius: 3.65,
    radius: 0.33,
    semiMajorAxisAu: 0.723,
    orbitalEccentricity: 0.007,
    orbitalInclinationDeg: 3.39,
    orbitalPeriodDays: 224.7,
    initialAngle: 78,
    orbitSpeed: 0.38,
    rotationSpeed: -0.003,
    inclination: 0.1,
    color: '#d69b56',
    accent: '#ffd89b',
    glow: '#ffbd73',
    shadow: '#70432e',
    textureMode: 'cloud',
  },
  {
    id: 'earth',
    order: '03',
    name: '地球',
    englishName: 'Earth',
    title: '蓝色生命视角',
    subtitle: '岩质行星 / 液态海洋',
    description: '地球是这套星图的默认观测点。海洋、云层和城市光在暗处形成可识别的生命信号。',
    insight: '点击“进入地球视角”，镜头会收紧到更近的观测距离。',
    metrics: [
      { label: '平均距离 (AU)', value: '1.00' },
      { label: '公转周期', value: '365.26 天' },
      { label: '自转周期', value: '23.93 小时' },
      { label: '直径', value: '12,742 km' },
      { label: '表面重力', value: '9.8 m/s²' },
      { label: '卫星数量', value: '1' },
    ],
    orbitStatus: [
      { label: '速度', value: '29.8 km/s' },
      { label: '轨道偏心率', value: '0.017' },
      { label: '近日点', value: '0.98 AU' },
      { label: '远日点', value: '1.02 AU' },
    ],
    orbitRadius: 4.75,
    radius: 0.42,
    semiMajorAxisAu: 1.0,
    orbitalEccentricity: 0.017,
    orbitalInclinationDeg: 0,
    orbitalPeriodDays: 365.26,
    initialAngle: 132,
    orbitSpeed: 0.3,
    rotationSpeed: 0.014,
    inclination: 0.08,
    color: '#4c8ac4',
    accent: '#86d9ff',
    glow: '#8ce8ff',
    shadow: '#193352',
    textureMode: 'ocean',
  },
  {
    id: 'mars',
    order: '04',
    name: '火星',
    englishName: 'Mars',
    title: '红色荒原与远征想象',
    subtitle: '岩质行星 / 稀薄大气',
    description: '氧化铁让火星呈现红色。峡谷、火山和极冠让它成为最具探索叙事感的邻居。',
    insight: '火星被选中时，红色外晕会强调它的远征气质。',
    metrics: [
      { label: '平均距离 (AU)', value: '1.52' },
      { label: '公转周期', value: '687 天' },
      { label: '自转周期', value: '24.6 小时' },
      { label: '直径', value: '6,779 km' },
      { label: '平均温度', value: '-63°C' },
      { label: '卫星数量', value: '2' },
    ],
    orbitStatus: [
      { label: '速度', value: '24.1 km/s' },
      { label: '轨道偏心率', value: '0.093' },
      { label: '近日点', value: '1.38 AU' },
      { label: '远日点', value: '1.67 AU' },
    ],
    orbitRadius: 5.95,
    radius: 0.31,
    semiMajorAxisAu: 1.524,
    orbitalEccentricity: 0.093,
    orbitalInclinationDeg: 1.85,
    orbitalPeriodDays: 686.98,
    initialAngle: 205,
    orbitSpeed: 0.24,
    rotationSpeed: 0.013,
    inclination: 0.18,
    color: '#b85b3c',
    accent: '#ff8a5c',
    glow: '#ff714b',
    shadow: '#54241d',
    textureMode: 'crater',
  },
  {
    id: 'jupiter',
    order: '05',
    name: '木星',
    englishName: 'Jupiter',
    title: '巨型风暴的重力剧场',
    subtitle: '气态巨行星 / 条带云层',
    description: '木星质量巨大，云带与大红斑像一台持续运转的风暴机器。它的尺度让整套星图有了压迫感。',
    insight: '提高公转速度时，木星的慢速运动会和内行星形成明显对比。',
    metrics: [
      { label: '平均距离 (AU)', value: '5.20' },
      { label: '公转周期', value: '11.86 年' },
      { label: '自转周期', value: '9.9 小时' },
      { label: '直径', value: '139,820 km' },
      { label: '大气主成分', value: '氢 / 氦' },
      { label: '卫星数量', value: '95+' },
    ],
    orbitStatus: [
      { label: '速度', value: '13.1 km/s' },
      { label: '轨道偏心率', value: '0.049' },
      { label: '近日点', value: '4.95 AU' },
      { label: '远日点', value: '5.46 AU' },
    ],
    orbitRadius: 7.55,
    radius: 0.74,
    semiMajorAxisAu: 5.203,
    orbitalEccentricity: 0.049,
    orbitalInclinationDeg: 1.3,
    orbitalPeriodDays: 4332.59,
    initialAngle: 252,
    orbitSpeed: 0.13,
    rotationSpeed: 0.021,
    inclination: 0.12,
    color: '#c88f5a',
    accent: '#ffd09a',
    glow: '#ffbd7a',
    shadow: '#5f3e2e',
    textureMode: 'storm',
  },
  {
    id: 'saturn',
    order: '06',
    name: '土星',
    englishName: 'Saturn',
    title: '环带切开的黄金星体',
    subtitle: '气态巨行星 / 行星环',
    description: '土星的环由冰粒和岩石碎片组成。它在画面中承担最强的轮廓识别和空间层次。',
    insight: '关闭轨道线后，土星环会成为画面中最清晰的结构线。',
    metrics: [
      { label: '平均距离 (AU)', value: '9.58' },
      { label: '公转周期', value: '29.45 年' },
      { label: '自转周期', value: '10.7 小时' },
      { label: '直径', value: '116,460 km' },
      { label: '环系宽度', value: '约 282,000 km' },
      { label: '卫星数量', value: '146+' },
    ],
    orbitStatus: [
      { label: '速度', value: '9.7 km/s' },
      { label: '轨道偏心率', value: '0.057' },
      { label: '近日点', value: '9.04 AU' },
      { label: '远日点', value: '10.12 AU' },
    ],
    orbitRadius: 9.2,
    radius: 0.63,
    semiMajorAxisAu: 9.537,
    orbitalEccentricity: 0.057,
    orbitalInclinationDeg: 2.49,
    orbitalPeriodDays: 10759.22,
    initialAngle: 316,
    orbitSpeed: 0.095,
    rotationSpeed: 0.018,
    inclination: 0.2,
    color: '#d1b37a',
    accent: '#f9d99b',
    glow: '#ffe2aa',
    shadow: '#6e6044',
    ring: true,
    textureMode: 'bands',
  },
  {
    id: 'uranus',
    order: '07',
    name: '天王星',
    englishName: 'Uranus',
    title: '横躺旋转的冰蓝行星',
    subtitle: '冰巨行星 / 高倾角',
    description: '天王星几乎横躺着自转，淡蓝绿色来自甲烷吸收红光。它让画面从暖色逐渐滑向冷色深处。',
    insight: '它的轨道在远处更安静，适合作为深空层次的冷光锚点。',
    metrics: [
      { label: '平均距离 (AU)', value: '19.2' },
      { label: '公转周期', value: '84 年' },
      { label: '自转周期', value: '17.2 小时' },
      { label: '直径', value: '50,724 km' },
      { label: '轴倾角', value: '97.8°' },
      { label: '卫星数量', value: '27' },
    ],
    orbitStatus: [
      { label: '速度', value: '6.8 km/s' },
      { label: '轨道偏心率', value: '0.046' },
      { label: '近日点', value: '18.3 AU' },
      { label: '远日点', value: '20.1 AU' },
    ],
    orbitRadius: 10.75,
    radius: 0.5,
    semiMajorAxisAu: 19.191,
    orbitalEccentricity: 0.046,
    orbitalInclinationDeg: 0.77,
    orbitalPeriodDays: 30685.4,
    initialAngle: 54,
    orbitSpeed: 0.067,
    rotationSpeed: -0.015,
    inclination: 0.32,
    color: '#84c8d0',
    accent: '#b7f6f1',
    glow: '#abfff6',
    shadow: '#30555b',
    textureMode: 'ice',
  },
  {
    id: 'neptune',
    order: '08',
    name: '海王星',
    englishName: 'Neptune',
    title: '深蓝风暴的边界',
    subtitle: '冰巨行星 / 高速风暴',
    description: '海王星是最远的八大行星，深蓝色和高速风暴让它像太阳系边缘的一枚冷色句点。',
    insight: '在宽屏上，海王星会停在画面高处，强调轨道深度。',
    metrics: [
      { label: '平均距离 (AU)', value: '30.1' },
      { label: '公转周期', value: '164.8 年' },
      { label: '自转周期', value: '16.1 小时' },
      { label: '直径', value: '49,244 km' },
      { label: '风速峰值', value: '2,100 km/h' },
      { label: '卫星数量', value: '14' },
    ],
    orbitStatus: [
      { label: '速度', value: '5.4 km/s' },
      { label: '轨道偏心率', value: '0.010' },
      { label: '近日点', value: '29.8 AU' },
      { label: '远日点', value: '30.4 AU' },
    ],
    orbitRadius: 12.3,
    radius: 0.48,
    semiMajorAxisAu: 30.07,
    orbitalEccentricity: 0.01,
    orbitalInclinationDeg: 1.77,
    orbitalPeriodDays: 60190,
    initialAngle: 18,
    orbitSpeed: 0.052,
    rotationSpeed: 0.016,
    inclination: 0.26,
    color: '#3f67bc',
    accent: '#8bb7ff',
    glow: '#78a9ff',
    shadow: '#172d66',
    textureMode: 'ice',
  },
];

export const solarBody: PlanetProfile = {
  id: 'sun',
  order: '00',
  name: '太阳',
  englishName: 'Sun',
  title: '太阳系的发光引力核心',
  subtitle: '恒星 / 等离子光冕',
  description: '太阳是整个系统的引力与光源中心。进入近景后，它以光冕、粒子和日面纹理呈现。',
  insight: '点击太阳可以直接进入恒星检视，观察发光表面和等离子光效。',
  metrics: [
    { label: '类型', value: 'G2V 恒星' },
    { label: '平均半径', value: '696,340 km' },
    { label: '表面温度', value: '约 5,500°C' },
    { label: '自转周期', value: '约 25-35 天' },
    { label: '系统角色', value: '引力 / 光源' },
    { label: '卫星数量', value: '0' },
  ],
  orbitStatus: [
    { label: '相对位置', value: '系统中心' },
    { label: '光达地球', value: '8.3 分钟' },
    { label: '辐射强度', value: '3.828e26 W' },
    { label: '引力影响', value: '八大行星' },
  ],
  orbitRadius: 0,
  radius: 1.06,
  semiMajorAxisAu: 0,
  orbitalEccentricity: 0,
  orbitalInclinationDeg: 0,
  orbitalPeriodDays: 1,
  initialAngle: 0,
  orbitSpeed: 0,
  rotationSpeed: 0.006,
  inclination: 0,
  color: '#ffb347',
  accent: '#ffd36a',
  glow: '#ffda86',
  shadow: '#7a3217',
  textureMode: 'storm',
};

export const sceneModes = ['观测', '漫游', '讲解'] as const;

export type SceneMode = (typeof sceneModes)[number];
